#!/usr/bin/env bash
#Write a Bash script that displays all active IPv4 IPs on the machine it’s executed on

ip -4 addr show | grep "inet " | awk '{print $2}'
#filter only the lines that contain "inet " and then print the second field of each line